version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "infrastructure"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
